### ISSUE TITLE
Question: Why do you use broad macs2 peak calling for all modalities?

### ISSUE THREAD

**Issue by andy3nieto** [bartosovic-lab/nanoscope#6]
Hello from Spain!
Thank you very much for this wonderful resource. I am currently in the midst of implementing your nanoscope pipeline, and was just wondering, why is it that you perform your peak calling with the same parameters for all 3 of your modalities (H3K27ac, H3K27me3, ATAC), rather than specify narrow peak calling, for example, for your H3K27ac and ATAC modalities.

Just for reference, i'll leave the code that I am commenting on below (from nanoscope/workflow/Snakefile_preprocess.smk):
`'macs2 callpeak -t {input} -g {params.macs_genome} -f BAMPE -n {wildcards.modality} --outdir {params.macs_outdir} --llocal 100000 --keep-dup 1 --broad-cutoff 0.1 --max-gap 1000 --broad 2>&1 '`

Thank you very much in advance!

**Comment by bartosovic-lab** [comment]
Hi Andrea,  Great question. There is no particular reason for this peak calling and it really depends on the modality what peak caller is the best. In my experience the current macs2 command works well both for H3K27ac and H3K27me3. Narrow peaks were a bit too restrictive for histone modifications in my opinion and gave some false negatives. 

Of course for ATAC-seq probably the default cellranger peak caller would work great. This is not implemented at the moment, but since nanoscope includes regular cellranger run, the cellranger peaks are part of the output and can be used in downstream analysis.

I hope this is helpful :) 

Marek
